let FlagsMap = {
    "AMD" : "am",
    "AUD" : "au",
    "AZN" : "az",
    "BGN" : "bg",
    "BRL" : "br",
    "BYN" : "by",
    "CAD" : "ca",
    "CHF" : "ch",
    "CNY" : "cn",
    "CZK" : "cz",
    "DKK" : "dk",
    "EUR" : "fr",
    "GBP" : "gb",
    "HKD" : "hk",
    "HUF" : "hu",
    "INR" : "in",
    "JPY" : "jp",
    "KGS" : "kg",
    "KRW" : "kr",
    "KZT" : "kz",
    "MDL" : "md",
    "NOK" : "bv",
    "PLN" : "pl",
    "RON" : "ro",
    "RUB" : "ru",
    "SEK" : "se",
    "SGD" : "sg",
    "TJS" : "tj",
    "TMT" : "tm",
    "TRY" : "tr",
    "UAH" : "ua",
    "USD" : "us",
    "UZS" : "uz",
    "ZAR" : "za",
};

export default FlagsMap;